feat: default to private nodes on gcp gke
kubefirst/gitops-template pull request #557
Opened 2023-08-30 18:13 UTC by cameronraysmith

You can enable gke private nodes, while retaining a public endpoint
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/private-cluster

```HCL
module "gke" {
  source                     = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster"
  enable_private_endpoint    = false
  enable_private_nodes       = true
```

This might be a workable and, at least slightly, more secure default near https://github.com/kubefirst/gitops-template/blob/ef737f88cf87216f05d8459da69d7d2d0f673b45/gcp-github/terraform/gcp/gke/main.tf#L12

2023-08-30 21:32 UTC, johndietz commented
quick note to express support of a contribution to change the gcp default in this direction - thanks for thinking through this @cameronraysmith. this would bring gcp into tighter alignment with how we have our aws eks ecosystem set up. 💯

2023-09-06 18:35 UTC, Claywd requested changes
couple of changes needed, otherwise it looks good.

2023-09-06 18:35 UTC, Claywd commented on gcp-gitlab/terraform/gcp/gke/nat.tf
> +  name    = "kubefirst-cloud-router"
```suggestion
name = "gke-cloud-router-${local.cluster_name}"
```

2023-09-06 18:35 UTC, Claywd commented on gcp-github/terraform/gcp/gke/nat.tf
> +  name                               = "kubefirst-nat-config"
```suggestion
name = "gke-nat-config-"${local.cluster_name}"
```

2023-09-06 19:57 UTC, cameronraysmith commented on gcp-gitlab/terraform/gcp/gke/nat.tf
> +  name    = "kubefirst-cloud-router"
applied

2023-09-06 20:02 UTC, cameronraysmith reviewed
updated

2023-09-06 20:07 UTC, Claywd approved these changes

2023-09-08 17:37 UTC, merged